### PR TITLE
feat(sync-actions/discount-codes): add validFrom and validUntil

### LINKED ISSUE #376: Add `validFrom` and `validUntil` to discount codes sync
### Description

This platform has the notion of time based validity of discount for cart discounts. This notion will be added to discount codes too. The sync-actions package should keep parity with these update actions.

### PR DESCRIPTION
**Pull request by tdeekens**
#### Summary

⚠️  Please do not merge yet until this feature is available in the platform ⚠️ 

Closes #376

### CODE REVIEW

**Comment by tdeekens** [comment]
As a site note. The naming of `typeIds` as in `typeId: 'new-cart-discount-1' and `typeId: 'previous-cart-discount'` is a bit "bizarre" as the those are not aligned with the platform's limited and specified set of type ids ([ref](https://dev.commercetools.com/http-api-types.html#reference-types)).

**Comment by wizzy25** [comment]
I will be putting this PR on hold until it's ready to be merged

**Comment by tdeekens** [comment]
Platform supports it now. Merging.

**Comment by wizzy25** [comment]
@tdeekens Maybe not yet. Still no documentation for it [here](http://dev.commercetools.com/http-api-projects-discountCodes.html)

**Comment by tdeekens** [comment]
Let's chat tomorrow. I will try to clarify when documentation comes. It will be in the next release of the platform. I observed the relating PR.

**Pull request merged**
