### PR TITLE
fix(auth): encode username and password for password flow

### LINKED ISSUE #839: Password flow doesn't accept `+` char in email
### Support reference number

https://jira.commercetools.com/browse/SUPPORT-4005

### Description

User email needs to be URI encoded

### PR DESCRIPTION
**Pull request by daern91**
#### Summary

PR encodes user email and password which the platform requires. More reading in these two threads ([1](https://jira.commercetools.com/browse/SUPPORT-4005) and [2](https://jira.commercetools.com/browse/CTP-1652)).

#### Todo

- Tests
  - [x] Integration

resolves #839

### CODE REVIEW

**Comment by junajan** [comment]
should we encode password too?

**Comment by daern91** [comment]
@junajan Why not, I guess. It seemed to work without it already, with that new complex password, but I'll add it anyways.

**Comment by lauraluiz** [comment]
I wonder how, though. It should not be working both with urlencoding and without it. At least I cannot make sense of it 🤔 
When you changed the email and added the `+`, before urlenconding it, was it failing?

**Comment by daern91** [comment]
You are completely right, @lauraluiz :-) 

I added a `+` to the password inside the int test and then it did, in fact, fail for me locally. So I updated the PR with encoded password and a `+` inside password now.

**Pull request merged**
