### PR TITLE
fix(sync-action): setDescription -> changeDescription

### PR DESCRIPTION
**Pull request by adnasa**
oops.

### CODE REVIEW

**Comment by adnasa** [comment]
@junajan 
that's not really the problem i'm solving here.
in the [docs](https://docs.commercetools.com/http-api-projects-productTypes.html#change-description) for product-types, the action to update the description is `changeDescription`

**Comment by dferber90** [comment]
Would it make sense to change this to `setDescription` in the API then (while keeping `changeDescription` around for backwards compatibility), and to not merge this PR?

**Comment by yanns** [comment]
`changeXxx` is used for non-optional fields, and `setXxx` is used for optional fields.
With `setXxx` you can remove a value.

**Comment by adnasa** [comment]
thanks for clarifying this!

**Comment by butenkor** [comment]
Price is optional but update action is called [changePrice](https://docs.commercetools.com/http-api-projects-products.html#change-price) and not setPrice. Same with `changeAssetOrder` and `changeAssetName`. Would be easier if only `set` is used.

**Pull request merged**
