### PR TITLE
docs(readme): add list of package names, versions and dependency status

### LINKED ISSUE #28: List packages in readme
List the packages with their link to the NPM page, version and dependency status in the readme.

### PR DESCRIPTION
**Pull request by Siilwyn**
Resolves #28

### CODE REVIEW

**Comment by Siilwyn** [comment]
Yeah that would be great but how do we differentiate between the different packages? E.g. once we have more packages we would maybe have some groups as: SDK, middlewares, CSV parsers, etc.
If it's all one big table it would be easy. Ideas on that?

**Comment by emmenko** [comment]
On the other hand, you might only need that when adding a new package. So maybe the script can simply print the information for 1 single package. Then you put it in the README wherever you want.
Not really a big issue anyway, more of a nice to have suggestion ;)

**Comment by Siilwyn** [comment]
@emmenko made a small script, indeed we only want to use it when adding a new package. Also looking at Babel they don't list all packages since some are never used directly by users so listing everything automatically is not ideal unless we filter out packages somehow.

**Comment by hisabimbola** [comment]
> Also looking at Babel they don't list all packages since some are never used directly by users
I am not sure how babel does it, but if it's a package that is published to NPM then we automatically assume that it being used. So maybe a good filter will be to check if the 'private' flag is false in the package.json

**Comment by Siilwyn** [comment]
@hisabimbola  Well if we follow Babel's way that wouldn't work. E.g. `babel-helper-regex` is published to npm but not listed in the readme.

**Comment by Siilwyn** [comment]
Abi noticed that the badges have a lot of timeouts it might be worth setting up a simple server that acts as a proxy with a cache. Maybe it's something I can do tomorrow with the tech time.

**Pull request merged**
