### PR TITLE
chore(package.json): deps installed

### PR DESCRIPTION
**Pull request by adnasa**
#### Summary

I received these changes locally after running `yarn release` 🤷‍♂ 
I'm not entirely sure if we should keep this.

feel free to just close the PR if it is irrelevant, but I'd like to hear what is going on here

### CODE REVIEW

**Comment by daern91** [comment]
I think they get installed by the `gitbook cli` when publishing the docs. No need to have them saved/installed for everyone so we could close it

**Comment by adnasa** [comment]
@daern91  oops... I was so eager :D 
remove them?

**Comment by daern91** [comment]
haha no problems. I dont mind keeping them tbh, we could just move them into the devdependencies. Probably better for onboarding anyway so its less confusing :-)

**Comment by daern91** [comment]
I also see that the linter is failing now :trollface:

**Pull request merged**
