### PR TITLE
fix: bump node js version

### PR DESCRIPTION
**Pull request by VineetKumarKushwaha**
### Current node js version has some vulnerability so bumped to the non vulnerable version

Fix: #1647

### CODE REVIEW

**Comment by VineetKumarKushwaha** [comment]
@daern91 @ashishhk I checked but didn't get anything why this test cases are failing. I can see the test cases are failing on node 12 on master as well. I tried to update the circle node 12 version but then it started throwing some new node related errors. So Can we merge this as this change does not breaking anything new ?  we can debug the test cases issue later as I can see it may need more debugging time.

**Review by ashishhk — APPROVED** [review]
Thank you for updaing.

**Comment by ashishhk** [comment]
@daern91 I don't see a issue merging this PR since the master was already failing with the test case, WDYT ?

**Comment by daern91** [comment]
This PR #1654 is also blocked by the tests being red on master. So I think it would be best to unblock master first then merge these two... just to make sure we're not piling on more bugs/failing tests with the upcoming PRs.

**Review by daern91 — APPROVED** [review]

**Pull request merged**
