### PR TITLE
feat(api-request-builder): add My Shopping Lists and My Payments services

### PR DESCRIPTION
**Pull request by sheepsteak**
#### Summary

- [x] Add [My Shopping Lists](https://docs.commercetools.com/http-api-projects-me-shoppingLists) and [My Payments](https://docs.commercetools.com/http-api-projects-me-payments) services
#### Description

These services are currently missing from the default services so to use them we have to add them as custom services. Since [My Cart](https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/default-services.js#L158) already exists in there I thought I would add these two as well to save us needing to do a custom service for each.
#### Todo

- Tests
  - [x] Unit
  - [x] Integration

### CODE REVIEW

**Comment by sheepsteak** [comment]
Before this gets merged can I add [MyCustomerProfile](https://docs.commercetools.com/http-api-projects-me-profile) too?

**Comment by Babanila** [comment]
> Before this gets merged can I add [MyCustomerProfile](https://docs.commercetools.com/http-api-projects-me-profile) too?

Thanks, but no need to add it now because `MyCustomerProfile` is still in the beta stage. [See docs](https://docs.commercetools.com/http-api-projects-me-profile)

**Comment by sheepsteak** [comment]
OK, but MyShoppingLists are in beta too. Also MyCarts is too according to the docs and that's already in. Do the docs just need updating.

**Comment by sheepsteak** [comment]
OK, I'll close this PR for now but keep the branch on my fork 😄

**Pull request closed without merging**
