### PR TITLE
sync actions for attribute group

### PR DESCRIPTION
**Pull request by jaikumar-tj**
#### Summary

Sync action for attribute groups.

#### Description

The Attribute groups feature was released to the public beta and this PR creates the necessary sync action. 

#### Todo

- Tests
  - [x] Unit
  - [ ] Integration
  - [ ] Acceptance
- [ ] Documentation
- [ ] `Type` label for the PR

### CODE REVIEW

**Review by ahmehri — APPROVED** [review]
❤️

**Review by tdeekens — APPROVED** [review]

**Comment by jaikumar-tj** [comment]
@tdeekens Do I need anyone else's approval? Do I need to add a changeset? I'm not sure about the procedure for this repo.

**Comment by tdeekens** [comment]
> @tdeekens Do I need anyone else's approval? Do I need to add a changeset? I'm not sure about the procedure for this repo.

1. Yes, you need a changeset.
2. Other approvals aren't needed.
3. You can release (by merging the PR) after.

**Comment by jaikumar-tj** [comment]
@tdeekens Could you help me here? I don't have permission to merge PR.

Screenshot 2023-07-20 at 08 25 52

**Pull request merged**
