### PR TITLE
feat(apiRequestBuilder): Add a support for ShoppingLists endpoint

### LINKED ISSUE #128: [api-request-builder] Add a support for ShoppingLists endpoint
### Description
We would like to add a support for ShoppingList endpoint on Impex and therefore we should add it also here to api-request-builder.

### Current Behavior
Not supported currently.

### Possible Solution
Add an endpoint specification to the list of default services [here](https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/default-services.js).

### PR DESCRIPTION
**Pull request by junajan**
#### Summary
Resolves #128 

#### Description
This PR adds a support for ShoppingLists endpoint.

#### Todo

- Tests
    - [x] Unit
    - [ ] Integration
    - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

**Comment by junajan** [comment]
Thx for a quick review..

**Comment by emmenko** [comment]
@junajan you didn't trigger a release from your squash commit. Did you read the contributing document https://github.com/commercetools/nodejs/blob/master/CONTRIBUTING.md?

**Comment by junajan** [comment]
Hello @emmenko I red it but this was the first time I was merging so I forgot how to trigger release. Is it right that I should add something like this?
```
feat(api-request-builder): Add a support for ShoppingLists endpoint #128 

affects: @commercetools/api-request-builder
```

**Comment by emmenko** [comment]
Yeah, too late now

**Comment by junajan** [comment]
Yep.. next time I will know..

**Pull request merged**
